# Generated by Django 2.2.7 on 2020-02-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField()),
                ('Category', models.CharField(choices=[('sh', 'Shirt'), ('tr', 'Trousers')], max_length=55)),
                ('Style', models.CharField(choices=[('ca', 'Casual'), ('gl', 'Looking')], max_length=55)),
                ('Rejection_rate', models.IntegerField(default=2)),
                ('Acception_rate', models.IntegerField(default=2)),
                ('Stock', models.IntegerField(default=10)),
                ('Red0rderquantity', models.IntegerField()),
                ('RedXS', models.IntegerField()),
                ('RedS', models.IntegerField()),
                ('RedM', models.IntegerField()),
                ('RedL', models.IntegerField()),
                ('RedXL', models.IntegerField()),
                ('RedXXL', models.IntegerField()),
                ('Blue0rderquantity', models.IntegerField()),
                ('BlueXS', models.IntegerField()),
                ('BlueS', models.IntegerField()),
                ('BlueM', models.IntegerField()),
                ('BlueL', models.IntegerField()),
                ('BlueXL', models.IntegerField()),
                ('BlueXXL', models.IntegerField()),
                ('Yellow0rderquantity', models.IntegerField()),
                ('YellowXS', models.IntegerField()),
                ('YellowS', models.IntegerField()),
                ('YellowM', models.IntegerField()),
                ('YellowL', models.IntegerField()),
                ('YellowXL', models.IntegerField()),
                ('YellowXXL', models.IntegerField()),
            ],
        ),
    ]
