# Generated by Django 2.2.7 on 2020-02-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ord',
            new_name='Order',
        ),
    ]
