# Generated by Django 2.2.7 on 2020-02-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200211_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Fit',
            field=models.CharField(choices=[('Slim', 'Slim'), ('Regular', 'Regular'), ('Super Slim', 'Super Slim')], default='Slim', max_length=55),
        ),
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='Category',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('trousers', 'Trousers'), ('jacket', 'Jacket')], max_length=55),
        ),
        migrations.AlterField(
            model_name='order',
            name='Style',
            field=models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal')], max_length=55),
        ),
    ]
