# Generated by Django 2.2.7 on 2020-02-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200211_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='lay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField(blank=True, null=True, unique=True)),
                ('Category', models.CharField(choices=[('shirt', 'Shirt'), ('trousers', 'Trousers'), ('jacket', 'Jacket')], max_length=55)),
                ('Style', models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal')], max_length=55)),
                ('Fit', models.CharField(choices=[('Slim', 'Slim'), ('Regular', 'Regular'), ('Super Slim', 'Super Slim')], default='Slim', max_length=55)),
                ('Red0rderquantity', models.IntegerField(blank=True, default=0, null=True)),
                ('Red38', models.IntegerField(blank=True, default=0, null=True)),
                ('Red40', models.IntegerField(blank=True, default=0, null=True)),
                ('Red42', models.IntegerField(blank=True, default=0, null=True)),
                ('Red44', models.IntegerField(blank=True, default=0, null=True)),
                ('Red46', models.IntegerField(blank=True, default=0, null=True)),
                ('Red48', models.IntegerField(blank=True, default=0, null=True)),
                ('Red50', models.IntegerField(blank=True, default=0, null=True)),
                ('Red52', models.IntegerField(blank=True, default=0, null=True)),
                ('Red54', models.IntegerField(blank=True, default=0, null=True)),
                ('Blue0rderquantity', models.IntegerField(blank=True, default=0, null=True)),
                ('Blue38', models.IntegerField(blank=True, default=0, null=True)),
                ('Blue40', models.IntegerField(blank=True, default=0, null=True)),
                ('Blue42', models.IntegerField(blank=True, default=0, null=True)),
                ('Blue44', models.IntegerField(blank=True, default=0, null=True)),
                ('Blue46', models.IntegerField(blank=True, default=0, null=True)),
                ('Blue48', models.IntegerField(blank=True, default=0, null=True)),
                ('Blue50', models.IntegerField(blank=True, default=0, null=True)),
                ('Blue52', models.IntegerField(blank=True, default=0, null=True)),
                ('Blue54', models.IntegerField(blank=True, default=0, null=True)),
                ('Yellow0rderquantity', models.IntegerField(blank=True, default=0, null=True)),
                ('Yellow38', models.IntegerField(blank=True, default=0, null=True)),
                ('Yellow40', models.IntegerField(blank=True, default=0, null=True)),
                ('Yellow42', models.IntegerField(blank=True, default=0, null=True)),
                ('Yellow44', models.IntegerField(blank=True, default=0, null=True)),
                ('Yellow46', models.IntegerField(blank=True, default=0, null=True)),
                ('Yellow48', models.IntegerField(blank=True, default=0, null=True)),
                ('Yellow50', models.IntegerField(blank=True, default=0, null=True)),
                ('Yellow52', models.IntegerField(blank=True, default=0, null=True)),
                ('Yellow54', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
