# Generated by Django 2.2.7 on 2020-02-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_lay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lay',
            name='Blue0rderquantity',
        ),
        migrations.RemoveField(
            model_name='lay',
            name='Red0rderquantity',
        ),
        migrations.RemoveField(
            model_name='lay',
            name='Yellow0rderquantity',
        ),
    ]
