# Generated by Django 2.1.7 on 2020-02-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20200220_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField(blank=True, null=True, unique=True)),
                ('Style', models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal')], max_length=55)),
                ('Roll_1', models.IntegerField(blank=True, default=0, null=True)),
                ('Roll_2', models.IntegerField(blank=True, default=0, null=True)),
                ('Roll_3', models.IntegerField(blank=True, default=0, null=True)),
                ('Roll_4', models.IntegerField(blank=True, default=0, null=True)),
                ('Roll_5', models.IntegerField(blank=True, default=0, null=True)),
                ('no_of_plies', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
