# Generated by Django 2.1.7 on 2020-02-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='lay_length',
            field=models.IntegerField(blank=True, default=1.5, null=True),
        ),
    ]
