# Generated by Django 2.1.7 on 2020-02-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_roll_lay_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='lay_length',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.5, max_digits=5, null=True),
        ),
    ]
